### ISSUE TITLE
cannot find package "github.com/cespare/xxhash/v2"

### ISSUE THREAD

**Issue by brunetton** [orange-cloudfoundry/custom_exporter#3]
Hi, I tried to install this exporter following the README but I came accross this:

```
> go get -u github.com/orange-cloudfoundry/custom_exporter
package github.com/cespare/xxhash/v2: cannot find package "github.com/cespare/xxhash/v2" in any of:
        /usr/lib/go-1.7/src/github.com/cespare/xxhash/v2 (from $GOROOT)
        /home/bruno/go/src/github.com/cespare/xxhash/v2 (from $GOPATH)
```

I suppose that I could simply replace "github.com/cespare/xxhash/v2" by "github.com/cespare/xxhash/" ? But I'm not a Go developer.

**Comment by brunetton** [comment]
Answering to myself: as stated [in this issue](https://github.com/prometheus/client_golang/issues/661), I need to upgrade go to version > `1.10.3+`

**Comment by nabbar** [comment]
I close this issue. 
Open new if you still having an error.
